chore: adds in disclaimers rnft
bosonprotocol/core-components pull request #433
Opened 2023-02-17 13:12 UTC by mischat

## Description

This adds in a disclaimer regarding the nature of the rNFT

## How to test

By checking the offer licences and offer t&cs

2023-02-17 13:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bosonprotocol/core-components?pullRequest=433) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bosonprotocol/core-components?pullRequest=433) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bosonprotocol/core-components?pullRequest=433) it.</sub>

2023-02-20 13:00 UTC, albertfolch-redeemeum approved these changes

2023-02-27 10:54 UTC, levalleux-ludo requested changes
The new templates need to be published on IPFS (using `npm run ipfs-upload ...`) , then the new hashes should be written in https://github.com/bosonprotocol/core-components/blob/main/data/ipfs.txt and then referenced in the dApp using the secret values REACT_APP_BUYER_SELLER_AGREEMENT_TEMPLATE_* and REACT_APP_RNFT_LICENSE_TEMPLATE_*

2023-09-19 11:21 UTC, mischat commented
@levalleux-ludo can you make this change ? Sorry i don't know how to merge and deploy it all ?

2023-10-10 13:38 UTC, levalleux-ludo commented
applied with https://github.com/bosonprotocol/interface/pull/876 and https://github.com/bosonprotocol/widgets/pull/77

2023-10-10 13:38 UTC, merged