fix: testing issues
bosonprotocol/core-components pull request #666
Opened 2024-02-15 17:37 UTC by albertfolch-redeemeum

2024-02-16 16:09 UTC, albertfolch-redeemeum commented on packages/react-kit/src/components/logo/useAssetLogoSource.ts
> +const hideLogo = false;
removed

2024-02-16 17:40 UTC, levalleux-ludo requested changes

2024-02-16 17:40 UTC, levalleux-ludo commented on packages/react-kit/src/hooks/contracts/erc1155/useErc1155Uri.ts
> +  });
```suggestion
  return useQuery(
    ["useErc1155Uri", coreSDK.uuid, props],
    async () => {
      const { contractAddress, tokenIds } = props;
      if (!contractAddress || !tokenIds) {
        return;
      }
      return Promise.all(
        tokenIds.map((tokenId) =>
          tokenId
            ? coreSDK.erc1155Uri({
                contractAddress,
                tokenId
              })
            : null
        )
      );
    },
    { enabled }
  );
```

2024-02-16 17:40 UTC, levalleux-ludo commented on packages/react-kit/src/hooks/contracts/erc721/useErc721TokenUri.ts
> +  });
```suggestion
  return useQuery(
    ["useErc721TokenUri", coreSDK.uuid, props],
    async () => {
      const { contractAddress, tokenIds } = props;
      if (!contractAddress || !tokenIds) {
        return;
      }
      return Promise.all(
        tokenIds.map((tokenId) =>
          tokenId
            ? coreSDK.erc721TokenUri({
                contractAddress,
                tokenId
              })
            : null
        )
      );
    },
    { enabled }
  );
```

2024-02-16 17:40 UTC, levalleux-ludo commented on packages/react-kit/src/hooks/contracts/erc721/useErc721TokenUri.ts
> +  });
And the same change is also required in
- packages/react-kit/src/hooks/contracts/erc721/useErc721OwnerOf.ts
- packages/react-kit/src/hooks/offer/useExchangeTokenBalance.ts

2024-02-19 09:51 UTC, levalleux-ludo approved these changes
LGTM

2024-02-19 09:53 UTC, merged