feat: exchange card visual changes
bosonprotocol/core-components pull request #867
Opened 2024-12-20 09:09 UTC by max-koz

## Description

{{what was done}}

## How to test

{{how can it be tested}}

2024-12-20 09:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bosonprotocol/core-components?pullRequest=867) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bosonprotocol/core-components?pullRequest=867) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bosonprotocol/core-components?pullRequest=867) it.</sub>

2024-12-20 10:44 UTC, albertfolch-redeemeum approved these changes

2025-01-17 16:37 UTC, albertfolch-redeemeum commented
check the updated design 
![image](https://github.com/user-attachments/assets/b203e2a2-028f-4788-8b76-15c79da3f9eb)

https://www.figma.com/design/XJTJYx5N9gsYSHTfL1167P/Roblox-Widget-%26-Landingpage?node-id=16076-68711&t=Qd7bUtm7N1fWkKIb-0

phygital label is under the asset name @MaksymilianKozak

2025-01-17 16:38 UTC, albertfolch-redeemeum commented
I didnt check but it seems that the seller should not be shown, maybe add a showSeller prop and make it false by default

2025-01-31 13:53 UTC, max-koz commented
<img width="372" alt="image" src="https://github.com/user-attachments/assets/16c61f2b-21d2-4ecc-9ddb-f1d3c155d9a0" />
<img width="584" alt="image" src="https://github.com/user-attachments/assets/4f20c6cb-a7b2-46a6-89ac-99500cb09cbf" />

2025-01-31 15:00 UTC, albertfolch-redeemeum commented
not sure why the GH doesnt fail here but this has to be fixed
<img width="1002" alt="image" src="https://github.com/user-attachments/assets/fe176596-79e2-471e-a39e-974fde549796" />

2025-02-03 10:59 UTC, albertfolch-redeemeum commented on packages/react-kit/src/components/productCard/ProductCard.tsx
> +          {productType === ProductType.phygital && PhygitalLabel()}
```suggestion
          {productType === ProductType.phygital && <PhygitalLabel/>}
```

2025-02-03 11:00 UTC, albertfolch-redeemeum commented on packages/react-kit/src/components/productCard/ProductCard.tsx
> +    hideCreatorName = true,
is it hidden in figma in both product and exchange cards?

2025-02-03 11:01 UTC, albertfolch-redeemeum commented on packages/react-kit/src/components/exchangeCard/ExchangeCard.tsx
> +              {isPhygital && PhygitalLabel()}
```suggestion
              {isPhygital && <PhygitalLabel/>}
```

2025-02-03 11:04 UTC, max-koz commented on packages/react-kit/src/components/productCard/ProductCard.tsx
> +    hideCreatorName = true,
It is hidden in Product card, Exchange Card has to be similar as Product according to latest task

2025-02-03 11:05 UTC, albertfolch-redeemeum requested changes
no border nor box-shadow 
![image](https://github.com/user-attachments/assets/ca3f0174-1a27-4004-bf19-c68d4675fc0e)

2025-02-03 11:05 UTC, albertfolch-redeemeum commented
also only 1 cta on hover like product card

2025-02-03 11:54 UTC, albertfolch-redeemeum commented
why does the product card have a top left label? 
![image](https://github.com/user-attachments/assets/7f063032-35fe-4a60-b41b-0e9b1d68b5cd)

2025-02-03 11:55 UTC, max-koz commented
> why does the product card have a top left label? ![image](https://private-user-images.githubusercontent.com/102516373/409092875-7f063032-35fe-4a60-b41b-0e9b1d68b5cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg1ODM5NTksIm5iZiI6MTczODU4MzY1OSwicGF0aCI6Ii8xMDI1MTYzNzMvNDA5MDkyODc1LTdmMDYzMDMyLTM1ZmUtNGE2MC1iNDFiLTBlOWIxZDY4YjVjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIwM1QxMTU0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDYxZDliMmFhZTY1NWM4YTk4ZWJjMWUxOTA3MDcyMjMwMDY3MzRmMjkzMjhkMTEzZDVjYzZkNDJhZTMxMzNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eH0zZalUDZS1SHuS0J07khLXaeFCRAk8mSpX5rF2KJg)

<img width="357" alt="image" src="https://github.com/user-attachments/assets/4094455f-e9cf-4c94-b7e2-124505aea495" />
It's like on figma

2025-02-03 11:56 UTC, albertfolch-redeemeum commented
cta still hasnt changed, this Dispute shouldnt be here, it should appear like in Product Card (this is roblox story btw)
![image](https://github.com/user-attachments/assets/d2f18b3c-39be-419b-8d63-ecf10b9ff603)

2025-02-03 15:07 UTC, max-koz commented
<img width="431" alt="image" src="https://github.com/user-attachments/assets/b20e69c6-f766-4143-a13f-094a0da9f792" />

2025-02-03 15:15 UTC, albertfolch-redeemeum commented
> <img alt="image" width="431" src="https://private-user-images.githubusercontent.com/109581727/409160466-b20e69c6-f766-4143-a13f-094a0da9f792.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg1OTU5NTksIm5iZiI6MTczODU5NTY1OSwicGF0aCI6Ii8xMDk1ODE3MjcvNDA5MTYwNDY2LWIyMGU2OWM2LWY3NjYtNDE0My1hMTNmLTA5NGEwZGE5Zjc5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIwM1QxNTE0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWRlZmQwNTZlNDFjMmY3ZmQyZmFjNjJjM2M4NzdjZjA1OTQ4ZDgyYmM4ZjgwY2M2NGY5OGQwMjZlM2UwZjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.t3wU4telUaykdmBcKKSTMJdmJFBMMADzj7-gg3SV2Zg">

can you fix the price wrapping?

2025-02-03 15:16 UTC, albertfolch-redeemeum commented
> > why does the product card have a top left label? ![image](https://private-user-images.githubusercontent.com/102516373/409092875-7f063032-35fe-4a60-b41b-0e9b1d68b5cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg1ODM5NTksIm5iZiI6MTczODU4MzY1OSwicGF0aCI6Ii8xMDI1MTYzNzMvNDA5MDkyODc1LTdmMDYzMDMyLTM1ZmUtNGE2MC1iNDFiLTBlOWIxZDY4YjVjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIwM1QxMTU0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDYxZDliMmFhZTY1NWM4YTk4ZWJjMWUxOTA3MDcyMjMwMDY3MzRmMjkzMjhkMTEzZDVjYzZkNDJhZTMxMzNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eH0zZalUDZS1SHuS0J07khLXaeFCRAk8mSpX5rF2KJg)
> 
> <img alt="image" width="357" src="https://private-user-images.githubusercontent.com/109581727/409093094-4094455f-e9cf-4c94-b7e2-124505aea495.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg1OTU5NTksIm5iZiI6MTczODU5NTY1OSwicGF0aCI6Ii8xMDk1ODE3MjcvNDA5MDkzMDk0LTQwOTQ0NTVmLWU5Y2YtNGM5NC1iN2UyLTEyNDUwNWFlYTQ5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIwM1QxNTE0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDQwZTBmN2M2YWExMTNmYmY0MjBiYjgyMzg0MWZlNTIxOGVlN2E4MjIxNmQwNDYzMWZkZmQ3ZjdkOGZhZGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BZfSkRMTP_V3cpNklHlifzVAmsrwgBuTES7pVZ3CrXo"> It's like on figma

that's an Exchange card not a product Card

2025-02-04 09:06 UTC, albertfolch-redeemeum commented
cancelButtonConfig in `packages/react-kit/src/components/exchangeCard/ExchangeCard.tsx` is not used because now there is only 1 cta, could you remove it and also check if there are others that need to be deleted for the same reason (and also delete them if so)?
@MaksymilianKozak

2025-02-04 09:07 UTC, albertfolch-redeemeum commented
I think you changed something about the label component related to the position, these changes should be done in the component that uses the label component to avoid these kind of bugs, could you fix that so that it looks good in the offer detail and also in the cards? (maybe what I said it's not the case, I havent checked) @MaksymilianKozak 

![image](https://github.com/user-attachments/assets/b4e90937-4fe3-4628-b551-030711c09e1e)

2025-02-04 10:03 UTC, merged